package tac;

public enum EnumType {
	// types simples
	SHORT, UNSIGNED_SHORT, INTEGER, UNSIGNED_INTEGER, 
	REAL, UNSIGNED_REAL, STRING, BOOLEAN, ENUM,
	
	// types complexes
	POINTER, FUNCTION, TIMES, 

	OP_ARITHMETIQUE, OP_BOOL,
    CHARACTER, CHARACTERS,
    TABLEAU, INTERVALLE, VARIABLE;
}
