
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 20 16:03:28 CET 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class CalculetteSymbol {
  /* terminals */
  public static final int INT = 11;
  public static final int SEMIC = 2;
  public static final int LPAR = 5;
  public static final int ENUM_BOOL = 10;
  public static final int AFFECT = 8;
  public static final int EOF = 0;
  public static final int ENUM_OP = 9;
  public static final int ID = 13;
  public static final int REAL = 12;
  public static final int error = 1;
  public static final int COMMA = 3;
  public static final int RPAR = 6;
  public static final int EQUALS = 4;
  public static final int ENUM_TYPE = 7;
}

