
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 19 10:47:06 CET 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class CalculetteSymbol {
  /* terminals */
  public static final int INT = 8;
  public static final int SEMIC = 2;
  public static final int LPAR = 5;
  public static final int EOF = 0;
  public static final int ID = 10;
  public static final int REAL = 9;
  public static final int error = 1;
  public static final int COMMA = 3;
  public static final int RPAR = 6;
  public static final int EQUALS = 4;
  public static final int ENUMTYPE = 7;
}

