
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 22 13:18:51 CET 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class CalculetteSymbol {
  /* terminals */
  public static final int TIMES = 15;
  public static final int MOD = 17;
  public static final int AND = 2;
  public static final int LT = 4;
  public static final int AFFECT = 21;
  public static final int PLUS = 13;
  public static final int INT = 30;
  public static final int LRBRA = 22;
  public static final int OR = 3;
  public static final int NOT = 10;
  public static final int LSBRA = 24;
  public static final int TRUE = 11;
  public static final int GT = 5;
  public static final int ID = 32;
  public static final int LE = 6;
  public static final int SEMIC = 26;
  public static final int EQUALS = 20;
  public static final int COMMA = 27;
  public static final int ENUM_TYPE = 28;
  public static final int MINUS_U = 18;
  public static final int EOF = 0;
  public static final int DIVIDE = 16;
  public static final int ENUM_OP = 29;
  public static final int FALSE = 12;
  public static final int GE = 7;
  public static final int MINUS = 14;
  public static final int error = 1;
  public static final int EQ = 8;
  public static final int RRBRA = 23;
  public static final int DIFF = 9;
  public static final int REAL = 31;
  public static final int NOT_U = 19;
  public static final int RSBRA = 25;
}

